name:  CICD
on:
  workflow_dispatch:
    branches:
      - master
  repository_dispatch:
     branches:
       - master  
       - test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
